#!/bin/bash
set -e

git fetch origin --prune

git branch --merged | grep -v main | xargs git branch -d
git branch -r --merged | awk -F'/' '/^ *origin/{if(!match($0, /(>|main)/)){print $2}}' | xargs git push origin --delete

git fetch origin --prune
