#!/bin/bash

# pre install:
# XCode, brew, visual studio code, brew install coreutils.

SCRIPT=$(realpath -s $0)
SCRIPTPATH=$(dirname $SCRIPT)

ln -f -s "$SCRIPTPATH/gvimrc.after" ~/.gvimrc.after

brew install tmux
brew install vim
brew install wget
brew install awk
brew install macvim
brew install ag

# Use starship for console
brew install starship
mkdir -p ~/.zsh/
ln -f -s "$SCRIPTPATH/git-completion.bash" ~/.zsh/git-completion.bash
ln -f -s "$SCRIPTPATH/git-completion.zsh" ~/.zsh/_git
mkdir -p ~/.config
ln -f -s "$SCRIPTPATH/starship.toml" ~/.config/starship.toml
ln -f -s "$SCRIPTPATH/zshrc" ~/.zshrc
ln -f -s "$SCRIPTPATH/zprofile" ~/.zprofile
ln -f -s "$SCRIPTPATH/agignore" ~/.agignore

cd ~/Downloads
git clone git://github.com/stephenway/monokai.terminal.git --depth=1
cd monokai.terminal
open Monokai.terminal
cd ~/Downloads
rm -rf monokai.terminal

git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ~/Downloads
rm -rf fonts

cd "$SCRIPTPATH"

ln -f -s "$SCRIPTPATH/gitconfig" ~/.gitconfig
touch projects
ln -f -s "$SCRIPTPATH/projects" ~/.projects
ln -f -s "$SCRIPTPATH/aliases" ~/.aliases
ln -f -s "$SCRIPTPATH/gemrc" ~/.gemrc
ln -f -s "$SCRIPTPATH/irbrc" ~/.irbrc
ln -f -s "$SCRIPTPATH/tmux.conf" ~/.tmux.conf
ln -f -s "$SCRIPTPATH/ackrc" ~/.ackrc

bash janus-bootstrap.sh

ln -f -s "$SCRIPTPATH/janus" ~/.janus
ln -f -s "$SCRIPTPATH/vimrc.after" ~/.vimrc.after
ln -f -s "$SCRIPTPATH/vimrc.before" ~/.vimrc.before
ln -f -s "$SCRIPTPATH/gvimrc.after" ~/.gvimrc.after

echo "rails development"

brew install rbenv
brew install postgresql
# brew install qt@5.5
echo "follow https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-high-sierra-1013-macos-sierra-1012-el-capitan-1011-and-yosemite-1010"

echo "Setting osx defaults"

# Show the ~/Library folder.
chflags nohidden ~/Library

# This will show all hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# Trackpad defaults
defaults -currentHost write -globalDomain com.apple.trackpad.fourFingerVertSwipeGesture -int 0
defaults -currentHost write -globalDomain com.apple.mouse.tapBehavior -int 1

# Disable press-and-hold for keys in favor of key repeat.
defaults write -g ApplePressAndHoldEnabled -bool false

# Always open everything in Finder's list view
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show the ~/Library folder.
chflags nohidden ~/Library

# Set a really fast key repeat.
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 2

# Set the Finder prefs for showing a few different volumes on the Desktop.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

#
# Keyboard shortcuts
#
#   ⌘⇧m   - to zoom the window
defaults write NSGlobalDomain NSUserKeyEquivalents -dict-add "Zoom" "@\$m"

echo "Restart finder to reload config"

killall -KILL Finder

# chsh -s /bin/zsh
