#!/bin/bash

dotfiles=$(dirname "$0")

brew install zsh
brew install tmux
brew install vim
brew install wget

git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
cd ~/.zprezto
git submodule update --init --recursive
git clone https://github.com/belak/prezto-contrib contrib
cd contrib
git submodule init
git submodule update
cd -

cd Downloads
git clone git://github.com/stephenway/monokai.terminal.git --depth=1
open monokai.terminal/Monokai.terminal
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd Downloads
rm -rf fonts
cd -


ln -f -s "$dotfile"/gitconfig ~/.gitconfig

touch projects
ln -f -s "$dotfile"/projects ~/.projects

ln -f -s "$dotfile"/aliases ~/.aliases

ln -f -s "$dotfile"/gemrc ~/.gemrc
ln -f -s "$dotfile"/irbrc ~/.irbrc

ln -f -s "$dotfile"/tmux.conf ~/.tmux.conf

wget https://raw.githubusercontent.com/thoughtbot/dotfiles/master/vimrc -O vimrc
ln -f -s "$dotfile"/vimrc ~/.vimrc
ln -f -s "$dotfile"/vimrc.local ~/.vimrc.local
wget https://raw.githubusercontent.com/thoughtbot/dotfiles/master/vimrc.bundles\
  -O vimrc.bundles
ln -f -s "$dotfile"/vimrc.bundles ~/.vimrc.bundles

ln -f -s ~/.zprezto/runcoms/zlogin ~/.zlogin
ln -f -s ~/.zprezto/runcoms/zlogout ~/.zlogout
ln -f -s  ~/.zprezto/runcoms/zprofile ~/.zprofile
ln -f -s ~/.zprezto/runcoms/zshenv ~/.zshenv
ln -f -s  "$dotfile"/zpreztorc ~/.zpreztorc
ln -f -s  "$dotfile"/zshrc ~/.zshrc

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
	curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa


echo "Mac Apps"

brew tap caskroom/cask
brew tap caskroom/versions

brew cask install virtualbox
brew cask install vagrant
brew cask install sublime-text
brew cask install slack
brew cask install google-chrome

echo "Use Docker4Mac"

# ensure docker-machine uninstalled
brew uninstall docker-machine
brew uninstall docker-engine

brew cask install docker

echo "rails development"

brew install rbenv
brew install postgresql
brew install qt@5.5

echo "Setting osx defaults"

# Show the ~/Library folder.
chflags nohidden ~/Library

# This will show all hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# Trackpad defaults
defaults -currentHost write -globalDomain com.apple.trackpad.fourFingerVertSwipeGesture -int 0
defaults -currentHost write -globalDomain com.apple.mouse.tapBehavior -int 1

# Disable press-and-hold for keys in favor of key repeat.
defaults write -g ApplePressAndHoldEnabled -bool false

# Always open everything in Finder's list view
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show the ~/Library folder.
chflags nohidden ~/Library

# Set a really fast key repeat.
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 2

# Set the Finder prefs for showing a few different volumes on the Desktop.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Run the screensaver if we're in the bottom-left hot corner.
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0

# Disable Notification Center and remove the menu bar icon
launchctl unload  \
  -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist \
  2> /dev/null
#
# Keyboard shortcuts
#
#   ⌘⇧m   - to zoom the window
defaults write NSGlobalDomain NSUserKeyEquivalents -dict-add "Zoom" "@\$m"

echo "Restart finder to reload config"

killall -KILL Finder

chsh -s /bin/zsh
