#!/bin/bash

brew install zsh
brew install tmux
brew install macvim --override-system-vim
brew install wget

git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto

pwd=$(pwd)

ln -f -s $pwd/gitconfig ~/.gitconfig

touch projects
ln -f -s $pwd/projects ~/.projects

ln -f -s $pwd/zshrc ~/.zshrc
ln -f -s $pwd/aliases ~/.aliases

ln -f -s $pwd/gemrc ~/.gemrc
ln -f -s $pwd/irbrc ~/.irbrc

ln -f -s $pwd/tmux.conf ~/.tmux.conf

wget https://raw.githubusercontent.com/thoughtbot/dotfiles/master/vimrc -O vimrc
ln -f -s $pwd/vimrc ~/.vimrc
ln -f -s $pwd/vimrc.local ~/.vimrc.local
wget https://raw.githubusercontent.com/thoughtbot/dotfiles/master/vimrc.bundles\
  -O vimrc.bundles
ln -f -s $pwd/vimrc.bundles ~/.vimrc.bundles

ln -f -s ~/.zprezto/runcoms/zlogin ~/.zlogin
ln -f -s ~/.zprezto/runcoms/zlogout ~/.zlogout
ln -f -s  ~/.zprezto/runcoms/zpreztorc ~/.zpreztorc
ln -f -s  ~/.zprezto/runcoms/zprofile ~/.zprofile
ln -f -s ~/.zprezto/runcoms/zshenv ~/.zshenv

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
	curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa



echo "Setting osx defaults"

# Always open everything in Finder's list view.
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Show the ~/Library folder.
chflags nohidden ~/Library

# This will show all hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# default apple: 0
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# default apple: 6
defaults write NSGlobalDomain KeyRepeat -int 6

# default apple: 25
defaults write NSGlobalDomain InitialKeyRepeat -int 25

# Trackpad defaults
defaults -currentHost write -globalDomain com.apple.trackpad.fourFingerVertSwipeGesture -int 0
defaults -currentHost write -globalDomain com.apple.mouse.tapBehavior -int 1

echo "Restart finder to reload config"

killall -KILL Finder


chsh -s /bin/zsh
